version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: go
    environment:
      - POSTGRES_USER=go
      - POSTGRES_PASSWORD=go
      - POSTGRES_DB=go
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5430:5432'
    volumes:
      - go:/var/lib/postgresql/data
    restart: always

volumes:
  go: